config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  resources :equipments, :attachments
  resources :orders do
    collection do
      delete 'destroy_multiple'
      get 'import_file'
      post 'import'
      post 'change_status'
      get 'change_status'
    end
  end
  resources :people do
    collection do
      delete 'destroy_multiple'
      get 'new_attachment'
      get 'download_attachment'
      post 'create_attachment'
    end
    member do
      get 'download_attachments'
    end
  end
  resources :alerts do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :bills do
    collection do
      delete 'destroy_multiple'
      get 'new_attachment'
      get 'download_attachment'
      post 'create_attachment'
    end
    member do
      get 'download_attachments'
    end
  end

  get "own_alerts" => "alerts#own"
  get "my_alerts" => "alerts#my"
  get "my_bills" => "bills#my"
  get "my_orders" => "orders#my"
  get "orders_cancelled_from_this_month" => "orders#orders_cancelled_from_this_month"
  get "orders_diagnosis_from_this_month" => "orders#orders_diagnosis_from_this_month"
  get "orders_repair_from_this_month" => "orders#orders_repair_from_this_month"
  get "orders_verification_from_this_month" => "orders#orders_verification_from_this_month"
  root 'panels#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  extend Search
  include GenerateCSV
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders, dependent: :restrict_with_error
  has_many :bills
  has_many :created_bills, class_name: "Bill", foreign_key: "created_by_id", dependent: :restrict_with_error
  has_many :attachments, :as => :attachmentable
  has_many :person_attachments, dependent: :destroy
  has_and_belongs_to_many :alerts
  belongs_to :role
  belongs_to :person_status
  before_create :set_default_person_status
  attr_accessor :login
  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  },
  format: {
    with: /\A[ążźćńęółśĄŻŹĆŃĘÓŁŚa-zA-Z0-9_\-\.]+\z/,
  }
  validates :username, :role, :name, :surname, :person_status, presence: true
  validates :pesel, numericality: { only_integer: true }, allow_blank: true
  validates_length_of :pesel, is: 11, allow_blank: true
  validate :validate_username, :check_nip
  validate :check_phone
  accepts_nested_attributes_for :person_attachments
  before_destroy { alerts.clear }
  scope :ten_best_people, -> {order("people.orders_count DESC").first(10)}

  def check_phone
    [:first_phone, :second_phone].each do |phone|
      phone_number = self.send(phone)
      unless phone_number.nil?
        unless phone_number.empty?
          if (7..16).include? phone_number.length
            errors.add(:phone_number, I18n.t('model_errors.phone_number', field: I18n.t('helpers.label.person.'+phone.to_s).downcase)) unless phone_number.strip.delete("() +-").is_number?
          else
            errors.add(:phone_number, I18n.t('model_errors.phone_number', field: I18n.t('helpers.label.person.'+phone.to_s).downcase))
          end
        end
      end
    end
  end

  def check_nip
    if self.nip != nil
      if self.nip.length > 0
        self.nip.strip!
        nip = self.nip.delete '-'
        unless nip.length == 10
          errors.add(:nip, I18n.t('model_errors.nip.wrong_number_of_digits'))
        end
        unless nip.is_number?
          errors.add(:nip, I18n.t('model_errors.nip.wrong_characters'))
        end
      end
    end
  end

  def get_name_and_surname_or_username
    if self.name.present?
      if self.surname.present?
        self.name + " " + self.surname
      else
        self.name
      end
    else
      if self.surname.present?
        self.surname
      else
        self.username
      end
    end
  end

  def has_role?(role_name)
    get_role == role_name
  end

  def get_role
    unless self.role.nil?
      self.role.name
    end
  end

  def get_person_status
    self.person_status.name
  end

  def admin?
    true if get_role == I18n.t('roles.admin') rescue false
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def validate_username
    if Person.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def email_required?
    false
  end

  #override devise method
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def self.special_fields_for_sort
    {
      "get_role": "roles.name"
    }
  end

  def self.search(search, role=nil)
    normal_fields = [:username, :email, :name, :surname, :nip, :pesel, :id_number, :workplace]
    special_fields = {
      role_id: [Role, :name]
    }
    super(search, normal_fields, special_fields, role)
  end

  private
  def set_default_person_status
    self.person_status ||= PersonStatus.find_by_name(I18n.t('person_statuses.active'))
  end
end

app/controllers/people_controller.rb
class PeopleController < GenericController
  before_action :all_people_and_roles, only: [:new, :edit, :update, :create]
  helper_method :current_user

  def new_attachment
    @person_attachments = @person.person_attachments
  end

  def create_attachment
    @person = Person.find(params[:person_id].first[0])
    params[:person_attachments]['attachment'].each do |a|
      @person_attachment = @person.person_attachments.create!(attachment: a, person_id: params[:person_id].first[0])
    end
    if @person_attachment.valid?
      flash[:success] = t('.success')
    else
      flash[:error] = t('.error')
    end
    redirect_to person_path(@person)
  end

  def destroy
    if current_user.id.to_s == params[:id]
      flash[:error] = t('.error_himself')
      redirect_to :back
    else
      super
    end
  end

  def destroy_multiple
    unless params[:people].nil?
      if params[:people].include? current_person.id.to_s
        flash[:error] = t('people.destroy.error_himself')
        redirect_to :back
      else
        super
      end
    else
      flash[:error] = t('people.destroy_multiple.no_checked')
      redirect_to :back
    end
  end

  def index
    respond_to do |format|
      super
      @people = @people.includes(:role)
      format.csv do
        send_data @people.to_csv
      end
      format.html
      format.pdf do
        pdf(I18n.t('.pdf.people') + "_#{I18n.t('.pdf.from')}_" + Time.new.strftime("%Y-%m-%d_%H-%M"))
      end
      format.xls
    end
  end

  def show
    respond_to do |format|
      format.csv do
        send_data Person.where(id: @person.id).to_csv
      end
      format.html
      format.pdf do
        pdf(I18n.t('.pdf.person') + "_" + @person.id.to_s + "_#{I18n.t('.pdf.from')}_" + Time.new.strftime("%Y-%m-%d_%H-%M"))
      end
      format.xls
    end

  end

  def update
    if params[:person][:password].blank? && params[:person][:password_confirmation].blank?
      params[:person].delete(:password)
      params[:person].delete(:password_confirmation)
    end
    unless current_user.admin?
      params[:person].delete(:role_id)
    end
    unless params[:person_attachments].nil?
      params[:person_attachments]['attachment'].each do |a|
        @person_attachment = @person.person_attachments.create!(attachment: a, person_id: @person.id)
      end
    end
    if current_user.admin?
      super
    else
      if @person.valid_password?(params[:person][:current_password])
        params[:person].delete(:current_password)
        super
      else
        flash[:error] = t('.wrong_password')
        render 'edit'
      end
    end
  end

  private
  def all_people_and_roles
    @people = Person.all.order(:surname, :name)
    @roles = Role.all.order(:name)
    @person_statuses = PersonStatus.all.order(:name)
    if @person.valid?
      @current_role = Role.where(name: @person.role.name).first
      @current_person_status = PersonStatus.where(name: @person.get_person_status).first
    else
      @current_role = nil
      @current_person_status = PersonStatus.where(name: t('person_statuses.active')).first
    end
  end

  def person_params
    params.require(:person).permit(:username, :password, :password_confirmation, :email, :company_name, :name, :surname, :nip, :pesel, :id_number, :workplace, :range_of_activity, :first_phone, :second_phone, :role_id, :person_status_id, :place, :address, person_attachments_attributes: [:id, :person_id, :attachment])
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<% unless @person.errors.messages.blank? %>
  <ul>
    <div class="block block-color danger">
      <div class="row">
        <div class="col-md-7 col-md-offset-2">
          <div class="header">
            <h3><%= I18n.t('people.error-header') %></h3>
          </div>
          <div class="content">
            <% @person.errors.messages.each do |field, messages| %>
              <% messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </ul>
<% end %>
<%= form_for @person, html: {class: "form-horizontal group-border-dashed", role:"form", novalidate:"", 'data-parsley-validate':"", multipart: true} do |f| %>
  <div class="form-group">
    <%= f.label :username, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
     <%= f.text_field :username, required: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-3 control-label", for:"inputEmail3" %>
    <div class="col-sm-6">
      <%= f.email_field :email, class: "form-control", id:"inputEmail3", type:"email"%>
    </div>
  </div>
  <% unless can? :manage, Person %>
    <% if action_name == 'edit' or action_name == 'update' %>
      <div class="form-group">
        <%= f.label :current_password, class: "col-sm-3 control-label" %>
        <div class="col-sm-6">
          <%= f.password_field :current_password, required: true, class: "form-control", type: "password" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if can? :update, Person %>
    <div class="form-group">
      <% if action_name == 'edit' or action_name == 'update' %>
        <%= f.label :new_password, class: "col-sm-3 control-label" %>
      <% else %>
        <%= f.label :password, class: "col-sm-3 control-label" %>
      <% end %>
      <div class="col-sm-6">
        <% if action_name == 'new' %>
          <%= f.password_field :password, required: true, class: "form-control", id: "pass1", 'data-parsley-equalto': "#pass2", type: "password" %>
        <% else %>
          <%= f.password_field :password, class: "form-control", id: "pass1", 'data-parsley-equalto': "#pass2", type: "password" %>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <% if action_name == 'edit' or action_name == 'update' %>
        <%= f.label :new_password_confirmation, class: "col-sm-3 control-label" %>
      <% else %>
        <%= f.label :password_confirmation, class: "col-sm-3 control-label" %>
      <% end %>
      <div class="col-sm-6">
        <% if action_name == 'new' %>
          <%= f.password_field :password_confirmation, required: true, class: "form-control", id: "pass2", 'data-parsley-equalto': "#pass1", type: "password" %>
        <% else %>
          <%= f.password_field :password_confirmation, class: "form-control", id: "pass2", 'data-parsley-equalto': "#pass1", type: "password" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :company_name, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :company_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :name, required: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :surname, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :surname, required: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nip, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :nip, class: "form-control", 'data-parsley-type': "digits", type: "text", 'data-parsley-length': "[10,10]" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :pesel, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :pesel, class: "form-control", 'data-parsley-type': "digits", type: "text", 'data-parsley-length': "[11,11]"%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :id_number, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :id_number, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :workplace, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :workplace, class: "form-control" %>
    </div>
  </div>
 <div class="form-group">
    <%= f.label :range_of_activity, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :range_of_activity, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :first_phone, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :first_phone, class: "form-control", placeholder: I18n.t('helpers.placeholder.phone_example') %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :second_phone, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :second_phone, class: "form-control", placeholder: I18n.t('helpers.placeholder.phone_example') %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :person_status, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.select :person_status_id, options_for_select(@person_statuses.collect{|s| [s.name, s.id]}, [@current_person_status.name, @current_person_status.id]), {}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :place, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :place, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <% if can? :manage, Person %>
    <div class="form-group">
      <%= f.label :get_role, class: "col-sm-3 control-label" %>
      <div class="col-sm-6">
        <% if !@current_role.nil? %>
          <%= f.select :role_id, options_for_select(@roles.collect{|r| [r.name, r.id]}, [@current_role.name, @current_role.id]), {}, class: "form-control" %>
        <% else %>
          <%= f.select :role_id, options_for_select(@roles.collect{|r| [r.name, r.id]}, []), {include_blank: ""}, class: "form-control", required: true %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.fields_for :person_attachments, @person.person_attachments.build do |b| %>
      <div class="form-group">
        <%= b.label :attachment, class: "col-sm-3 control-label" %>
        <div class="col-sm-6 file_field">
          <%= b.file_field :attachment, multiple: true, name: "person_attachments[attachment][]", type: "file", class: "filestyle" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <div class="col-sm-9">
      <div class="pull-right">
        <%= link_to I18n.t('helpers.link_to.cancel'), :back, class: "btn btn-default btn-rad" %>
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>
<% content_for :js_scripts do %>
  <script type="text/javascript">
    $(":file").filestyle('buttonText', "Wybierz załączniki");
    $("#pass1").focusout(function(){
      $("#pass2").parsley().reset();
    });
    $("#pass2").focusout(function(){
      $("#pass1").parsley().reset();
    });
  </script>
<% end %>

app/views/people/_form.pdf.erb
<h1>
  <b><%= I18n.t('.pdf.person') + " " + I18n.t('.pdf.number') + " " + person.id.to_s %></b>
</h1>
<table>
  <% [:email, :username, :company_name, :name, :surname, :nip, :pesel, :id_number, :workplace, :range_of_activity, :first_phone, :second_phone, :get_role, :get_person_status, :place, :address, :last_sign_in_at].each do |field| %>
    <% unless person.send(field).blank? %>
      <tr><td><%= I18n.t("helpers.label.person.#{field}") %>:</td><td><%= person.send(field) %></td></tr>
    <% end %>
  <% end %>
</table>

app/views/people/edit.html.erb
<div class="cl-mcont">
  <div class="row">
    <div class="col-md-12">
      <div class="block-flat">
        <div class="header">
          <h3><%= I18n.t('headlines.' + controller_name.singularize + '.edit') %></h3>
        </div>
        <div class="content">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/index.html.erb
<div class="cl-mcont">
  <div class="row">
    <div class="col-md-12">
      <div class="block-flat">
        <div class="header">
          <h3><%= I18n.t('headlines.' + controller_name.singularize + '.index') %></h3>
        </div>
        <div class="content">
          <div class="table-responsive">
            <div id="datatable_wrapper" class="dataTables_wrapper form-inline" role="grid">
              <div class="row">
                <div class="col-sm-12">
                  <div id="datatable_filter" class="dataTables_filter">
                    <%= render 'search/form' %>
                <%= form_tag destroy_multiple_people_path, method: :delete do %>
                 <div class="buttons-list-edit">
                  <%= link_to I18n.t('helpers.link_to.person.create'), new_person_path, class:"btn btn-success btn-rad" if can? :new, Person %>
                    <% unless @people.nil? %>
                      <%= submit_tag I18n.t('helpers.link_to.person.destroy_multiple'), data: {confirm: I18n.t('helpers.link_to.person.destroy_multiple_message')}, class:"btn btn-danger btn-rad" if can? :destroy, Person %>
                    <% end %>
                    <% if can? :show, @person %>
                        <div class="btn-group">
                          <button type="button" class="btn btn-info" data-toggle="dropdown"><%= I18n.t('helpers.link_to.download') %></button>
                          <button aria-expanded="false" type="button" class="btn btn-info btn-mono2 dropdown-toggle" data-toggle="dropdown">
                          <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu" role="menu">
                            <li><%= link_to I18n.t('helpers.link_to.download_pdf'), people_path(format: :pdf, search: params[:search], per_page: params[:per_page], direction: params[:direction], sort: params[:sort], page: params[:page]) %></li>
                            <li><%= link_to I18n.t('helpers.link_to.download_csv'), people_path(format: :csv, search: params[:search], per_page: params[:per_page], direction: params[:direction], sort: params[:sort], page: params[:page]) %></li>
                            <li><%= link_to I18n.t('helpers.link_to.download_xls'), people_path(format: :xls, search: params[:search], per_page: params[:per_page], direction: params[:direction], sort: params[:sort], page: params[:page]) %></li>
                          </ul>
                        </div>
                    </div>
                      <% end %>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </div>
                <table aria-describedby="datatable_info" class="table table-bordered dataTable" id="datatable">
                  <thead>
                    <tr role="row">
                      <th><div class="checkbox checkbox-primary"><%= check_box_tag "selectAll", "selectAll" %><label for="checkbox1"></label></div></th>
                        <% [:id, :username, :email, :name, :surname, :nip, :pesel, :id_number, :workplace, :get_role].each do |column| %>
                        <%= sortable column, I18n.t('helpers.label.person.' + column.to_s) %>
                      <% end %>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% unless @people.nil? %>
                      <% @people.each do |person| %>
                        <tr>
                          <td><div class="checkbox checkbox-info"><%= check_box_tag "people[]", person.id %><label for="checkbox1"></label></div></td>
                          <td><%= link_to person.id, person_path(person.id) %></td>
                          <td><%= link_to person.username, person_path(person.id) %></td>
                            <% [:email, :name, :surname, :nip, :pesel, :id_number, :workplace, :get_role].each do |col| %>
                            <% if ![:get_role].include? col %>
                              <td> <%= person.send(col) %></td>
                            <% else %>
                              <td><%= person.get_role %></td>
                            <% end %>
                          <% end %>
                          <td class="text-center">
                            <% if can? :show, person and !person.person_attachments.empty? %>
                              <%= link_to download_attachments_person_path(person) do %>
                                <i class="fa fa-paperclip"></i>
                              <% end %>
                            <% end %>
                            <% if can? :update, person %>
                              <%= link_to edit_person_path(person) do %>
                                <i class="fa fa-pencil"></i>
                              <% end %>
                            <% end %>
                            <% if can? :destroy, person %>
                              <%= link_to person_path(person), method: :delete, data: {confirm: I18n.t('helpers.link_to.person.destroy_single_message', person: person.get_name_and_surname_or_username)} do %>
                                <i class="fa fa-times"></i>
                              <% end %>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    <% end %>
                  </tbody>
                </table>
                <div class="form-pagination">
                  <% unless @people.nil? %>
                    <%= will_paginate @people %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for :js_scripts do %>
  <script>
    $('#selectAll').click(function() {
       if (this.checked) {
           $(':checkbox').each(function() {
               this.checked = true;
           });
       } else {
          $(':checkbox').each(function() {
               this.checked = false;
           });
       }
    });
  </script>
<% end %>

app/views/people/show.html.erb
<div class="cl-mcont">
  <div class="row">
    <div class="col-md-12">
      <div class="block-flat single-person">
        <div class="header">
          <h2><%= @person.get_name_and_surname_or_username %></h2>
          <h5><%= @person.username %></h5>
        </div>
        <div class="content">
        </div>
      </div>
    </div>
  </div>
</div>
<div class="cl-mcont user-data">
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <div class="tab-container">
        <ul class="nav nav-tabs">
          <li class="active"><a aria-expanded="true" href="#osobowe" data-toggle="tab">Dane osobowe</a></li>
          <li class=""><a aria-expanded="false" href="#firmowe" data-toggle="tab">Dane firmowe</a></li>
          <li class=""><a aria-expanded="false" href="#pozostale" data-toggle="tab">Pozostałe</a></li>
          <li class=""><a aria-expanded="false" href="#attachment" data-toggle="tab">Załączniki</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane cont active" id="osobowe">
              <div class="content">
                <table class="no-border">
                  <thead class="no-border">
                   <tr>
                      <td class="group-data">Dane personalne</td>
                      <td>Imię</td>
                      <td><%= @person.name %></td>
                    </tr>
                    <% [:surname, :nip, :pesel, :id_number].each do |row| %>
                    <tr>
                      <td></td>
                      <td><%=  I18n.t('helpers.label.person.' + row.to_s) %></td>
                      <td><%= @person.send(row) %></td>
                    </tr>
                    <% end %>
                    <tr>
                      <td class="group-data">Adres</td>
                      <td>Miejscowość</td>
                      <td><%= @person.place %></td>
                    </tr>
                    <tr>
                      <td></td>
                      <td><%= I18n.t('helpers.label.person.address') %></td>
                      <td><%= @person.address %></td>
                    </tr>
                    <% [:first_phone, :second_phone, :email].each do |row| %>
                      <tr>
                        <% if row == "first_phone" %>
                          <td class="group-data">Kontakt</td>
                        <% else %>
                          <td></td>
                        <% end %>
                        <td><%=  I18n.t('helpers.label.person.' + row.to_s) %></td>
                        <td><%= @person.send(row) %></td>
                      </tr>
                    <% end %>
                  </thead>
                </table>
            </div>
          </div>
          <div class="tab-pane cont" id="firmowe">
            <div class="content">
                <table class="no-border">
                  <thead class="no-border">
                    <tr>
                      <td class="group-data">Dane Firmowe</td>
                      <td>Nazwa Firmy</td>
                      <td><%= @person.company_name %></td>
                    </tr>
                    <% [:workplace, :range_of_activity, :get_person_status].each do |row| %>
                    <tr>
                      <td></td>
                      <td><%=  I18n.t('helpers.label.person.' + row.to_s) %></td>
                      <td><%= @person.send(row) %></td>
                    </tr>
                    <% end %>
                  </thead>
                </table>
            </div>
          </div>
          <div class="tab-pane cont" id="pozostale">
            <div class="content">
                <table class="no-border">
                  <thead class="no-border">
                    <tr>
                      <td class="group-data">Pozostałe informacje</td>
                      <td>Nazwa użytkownika</td>
                      <td><%= @person.username %></td>
                    </tr>
                    <% [:id, :last_sign_in_at, :get_role].each do |row| %>
                    <tr>
                      <td></td>
                      <td><%=  I18n.t('helpers.label.person.' + row.to_s) %></td>
                      <td><%= @person.send(row) %></td>
                    </tr>
                    <% end %>
                  </thead>
                </table>
            </div>
          </div>
          <div class="tab-pane cont" id="attachment">
              <div class="content">
                <table class="no-border">
                  <thead class="no-border">
                     <td></td><td></td>
                      <% @person.person_attachments.each do |a| %>
                        <tr>
                          <td><%= link_to I18n.t('helpers.label.person.attachment_number') + a.id.to_s, download_attachment_people_path(a) %></td>
                          <td><%= link_to I18n.t('helpers.label.person.attachment_remove'), attachment_path(a), method: :delete, data: {confirm: I18n.t('helpers.link_to.person.attachment_destroy_message', number: a.id)} %></td>
                        </tr>
                      <% end %>
                      <tr>
                        <td><%= link_to I18n.t('helpers.link_to.person.attachment_create'), new_attachment_people_path(id: @person.id) %></td>
                        <td><%= link_to I18n.t('helpers.link_to.person.attachments_download'),download_attachments_person_path(@person) unless @person.person_attachments.empty? %></td>
                      </tr>
                  </thead>
                </table>
            </div>
          </div>
        </div>
      </div>

      <% if can? :update, @person %>
        <%= link_to I18n.t('helpers.link_to.edit') + " #{@person.get_name_and_surname_or_username}", edit_person_path(@person), class:"btn btn-success" %>
      <% end %>
      <% if can? :destroy, @person %>
        <%= link_to I18n.t('helpers.link_to.destroy') + " #{@person.get_name_and_surname_or_username}", person_path(@person), method: :delete, data: {confirm:  I18n.t('helpers.link_to.person.destroy_single_message', person: @person.get_name_and_surname_or_username)}, class:"btn btn-danger" %>
      <% end %>
      <% if can? :show, @person %>
        <div class="btn-group">
          <button type="button" class="btn btn-info" data-toggle="dropdown"><%= I18n.t('helpers.link_to.download') %></button>
            <button aria-expanded="false" type="button" class="btn btn-info btn-mono2 dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to I18n.t('helpers.link_to.download_pdf'), person_path(format: :pdf) %></li>
              <li><%= link_to I18n.t('helpers.link_to.download_csv'), person_path(format: :csv) %></li>
              <li><%= link_to I18n.t('helpers.link_to.download_xls'), person_path(format: :xls) %></li>
            </ul>
        </div>
        <div class="blank-margin"></div>
      <% end %>
    </div>
  </div>
</div>