config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  resources :equipments, :attachments
  resources :orders do
    collection do
      delete 'destroy_multiple'
      get 'import_file'
      post 'import'
      post 'change_status'
      get 'change_status'
    end
  end
  resources :people do
    collection do
      delete 'destroy_multiple'
      get 'new_attachment'
      get 'download_attachment'
      post 'create_attachment'
    end
    member do
      get 'download_attachments'
    end
  end
  resources :alerts do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :bills do
    collection do
      delete 'destroy_multiple'
      get 'new_attachment'
      get 'download_attachment'
      post 'create_attachment'
    end
    member do
      get 'download_attachments'
    end
  end

  get "own_alerts" => "alerts#own"
  get "my_alerts" => "alerts#my"
  get "my_bills" => "bills#my"
  get "my_orders" => "orders#my"
  get "orders_cancelled_from_this_month" => "orders#orders_cancelled_from_this_month"
  get "orders_diagnosis_from_this_month" => "orders#orders_diagnosis_from_this_month"
  get "orders_repair_from_this_month" => "orders#orders_repair_from_this_month"
  get "orders_verification_from_this_month" => "orders#orders_verification_from_this_month"
  root 'panels#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  extend Search
  include GenerateCSV
	belongs_to :person
  belongs_to :bill_status
	has_many :attachments, :as => :attachmentable
  has_many :bill_attachments
  scope :alert_unpaid, -> { where("bill_status_id = ?", BillStatus.find_by_name(I18n.t('bill_statuses.unpaid')).id).order("issued_date desc") }
  scope :my_bills, lambda { |current_person| where(person_id: current_person) }
  validates :number, :bill_status_id, presence: true
  validate :check_amount, :check_date_of_payment
  accepts_nested_attributes_for :bill_attachments

  def check_amount
    unless self.amount.nil?
      if self.amount < 0
        errors.add(:amount,  I18n.t('model_errors.amount'))
      end
    end
  end

  def check_date_of_payment
    date_of_payment = self.date_of_payment
    unless date_of_payment.nil?
      unless date_of_payment == ""
        unless self.issued_date.nil?
          if date_of_payment < self.issued_date
            errors.add(:date_of_payment, I18n.t('model_errors.date_of_payment'))
          end
        end
      end
    end
  end

  def get_bill_status
    unless self.bill_status.nil?
      self.bill_status.name
    end
  end

  def get_person
    unless self.person.nil?
      self.person.get_name_and_surname_or_username
    end
  end

  def self.search(search, range)
    normal_fields = [:id, :number, :issued_date, :date_of_payment, :amount]
    special_fields = {
      person_id: [Person, [:name, :surname]],
      bill_status_id: [BillStatus, :name]
    }
    super(search, normal_fields, special_fields, range)
  end

  def self.special_fields_for_sort
    {
      "get_person": "people.surname",
      "get_bill_status": "bill_statuses.name"
    }
  end
end

app/controllers/bills_controller.rb
class BillsController < GenericController
  before_action :all_people_and_bill_statuses, only: [:new, :create, :edit, :update]

  def create
    params[:bill][:person_id] = params[:person_id]
    params[:bill][:created_by_id] = current_person.id
    super
  end

  def create_attachment
    @bill = Bill.find(params[:bill_id].first[0])
    params[:bill_attachments]['attachment'].each do |a|
      @bill_attachment = @bill.bill_attachments.create!(attachment: a, bill_id: params[:bill_id].first[0])
    end
    if @bill_attachment.valid?
      flash[:success] = t('.success')
    else
      flash[:error] = t('.error')
    end
    redirect_to bill_path(@bill)
  end

  def destroy
    request_hash = Rails.application.routes.recognize_path(URI(request.referer).path)
    if @bill.present? and @bill.destroy
      flash[:success] = t('.success')
      if can? request_hash[:action].to_sym, request_hash[:controller].singularize.titleize and request_hash[:action] != "show"
        redirect_to request_hash
      elsif can? :index, Bill
        redirect_to bills_path
      else
        redirect_to root_path
      end
    else
      flash[:error] = t('.error')
      if @bill.present?
        if can? request_hash[:action].to_sym, request_hash[:controller].singularize.titleize and request_hash[:action] != "show"
          redirect_to request_hash
        elsif can? :show, Bill
          redirect_to bill_path(@bill)
        else
          redirect_to root_path
        end
      else
        if can? request_hash[:action].to_sym, request_hash[:controller].singularize.titleize and request_hash[:action] != "show"
          redirect_to request_hash
        elsif can? :index, Bill
          redirect_to bills_path
        else
          redirect_to root_path
        end
      end
    end
  end

  def index
    respond_to do |format|
      super
      @bills = @bills.includes(:person, :bill_status)
      format.csv do
        send_data @bills.to_csv
      end
      format.html
      format.pdf do
        pdf(I18n.t('.pdf.bills') + "_#{I18n.t('.pdf.from')}_" + Time.new.strftime("%Y-%m-%d_%H-%M"))
      end
      format.xls
    end
  end

  def my
    @bills = Bill.my_bills(current_person).includes(:person, :bill_status).search(params[:search], params[:date_range]).order(sort_column + " " + sort_direction).paginate(page: params[:page],:per_page => @per_page)
    render :index
  end

  def new_attachment
    @bill_attachments = @bill.bill_attachments
  end

  def show
    respond_to do |format|
      format.csv do
        send_data Bill.where(id: @bill.id).to_csv
      end
      format.html
      format.pdf do
        pdf(I18n.t('.pdf.bill') + "_" + @bill.id.to_s + "_#{I18n.t('.pdf.from')}_" + Time.new.strftime("%Y-%m-%d_%H-%M"))
      end
      format.xls
    end
  end

  def update
    params[:bill][:person_id] = params[:person_id] unless params[:person_id].nil?
    unless params[:bill_attachments].nil?
      params[:bill_attachments]['attachment'].each do |a|
        @bill_attachment = @bill.bill_attachments.create!(attachment: a, bill_id: @bill.id)
      end
    end
    super
  end

  private
  def all_people_and_bill_statuses
    @bill_statuses = BillStatus.all.order(:name)
    @partners = Person.where(role: Role.find_by_name(I18n.t('roles.partner')))
    unless @bill.person_id.nil?
      @actual_partner = @bill.person_id
    end
    if @bill.valid?
      @actual_bill_status = @bill.bill_status_id
    else
      @actual_bill_status = ""
    end
  end

  def bill_params
    params.require(:bill).permit(:number, :issued_date, :date_of_payment, :amount, :person_id, :created_by_id, :bill_status_id, bill_attachments_attributes: [:id, :bill_id, :attachment])
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<ul>
  <% @bill.errors.messages.each do |field, messages| %>
    <% messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
</ul>
<%= form_for @bill, html: {multipart: true, class: "form-horizontal group-border-dashed", role:"form", novalidate:"", 'data-parsley-validate':""} do |f| %>
  <div class="form-group">
    <%= f.label :number, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :number, required: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :issued_date, class: "col-sm-3 control-label"%>
    <div class="col-sm-6">
      <div class="input-group date datetime" id="datetimepicker_bill1">
        <% if action_name == "new" %>
          <%= f.text_field :issued_date, class: 'form-control', value: DateTime.now.day.to_s.rjust(2, "0") + "-" + DateTime.now.month.to_s.rjust(2, "0") + "-" + DateTime.now.year.to_s.rjust(2, "0") %>
        <% else %>
          <%= f.text_field :issued_date, class: 'form-control' %>
        <% end %>
        <span class="input-group-addon btn btn-primary"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_of_payment, class: "col-sm-3 control-label"%>
    <div class="col-sm-6">
      <div class="input-group date datetime" id="datetimepicker_bill2">
        <%= f.text_field :date_of_payment, class: 'form-control' %>
        <span class="input-group-addon btn btn-primary"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
    </div>
  </div>
    <div class="form-group">
    <%= f.label :person_id, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= select_tag :person_id, options_for_select(@partners.collect{|p| [p.get_name_and_surname_or_username, p.id]}, [@actual_partner]), {include_blank: "", class: "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :amount, step: "0.01", min: 0, class: "form-control", 'parsley-type': "number" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bill_status_id, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.select :bill_status_id, options_for_select(@bill_statuses.collect{|bs| [bs.name, bs.id]}, [@actual_bill_status]), {include_blank: ""}, required: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.fields_for :bill_attachments, @bill.bill_attachments.build do |b| %>
      <div class="form-group">
        <%= b.label :attachment, class: "col-sm-3 control-label" %>
        <div class="col-sm-6 file_field">
          <%= b.file_field :attachment, multiple: true, name: "bill_attachments[attachment][]", type: "file", class: "filestyle" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <div class="col-sm-9">
      <div class="pull-right">
      <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/bills/_form.pdf.erb
<h1>
  <b><%= I18n.t('.pdf.bill') + " " + I18n.t('.pdf.number') + " " + bill.id.to_s %></b>
</h1>
<table>
  <% [:number, :issued_date, :date_of_payment, :amount, :get_person, :get_bill_status].each do |field| %>
    <% unless bill.send(field).blank? %>
      <tr><td><%= I18n.t("helpers.label.bill.#{field}") %>:</td><td><%= bill.send(field) %></td></tr>
    <% end %>
  <% end %>
</table>

app/views/bills/edit.html.erb
<div class="cl-mcont">
  <div class="row">
    <div class="col-md-12">
      <div class="block-flat">
        <div class="header">
          <h3><%= I18n.t('headlines.' + controller_name.singularize + '.edit') %></h3>
        </div>
        <div class="content">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bills/index.html.erb
<div class="cl-mcont">
  <div class="row">
    <div class="col-md-12">
      <div class="block-flat">
        <div class="header">
          <h2><%= I18n.t('headlines.' + controller_name.singularize + '.index') %></h2>
        </div>
        <div class="content">
          <div class="table-responsive">
            <div id="datatable_wrapper" class="dataTables_wrapper form-inline" role="grid">
              <div class="row">
                <div class="col-sm-12">
                  <div id="datatable_filter" class="dataTables_filter">
                    <%= render 'search/form', special_path: request.original_url.split("/").last.split("?").first %>
                <%= form_tag destroy_multiple_bills_path, method: :delete do %>
                 <div class="buttons-list-edit">
                  <%= link_to I18n.t('helpers.link_to.bill.create'), new_bill_path, class:"btn btn-success btn-rad" if can? :new, Bill %>
                  <% unless @bills.nil? %>
                    <%= submit_tag I18n.t('helpers.link_to.bill.destroy_multiple'), data: {confirm: I18n.t('helpers.link_to.bill.destroy_multiple_message')}, class:"btn btn-danger btn-rad" if can? :destroy, Bill %>
                  <% end %>
                  <% if can? :show, @bill %>
                    <div class="btn-group">
                      <button type="button" class="btn btn-info" data-toggle="dropdown"><%= I18n.t('helpers.link_to.download') %></button>
                      <button aria-expanded="false" type="button" class="btn btn-info btn-mono2 dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to I18n.t('helpers.link_to.download_pdf'), bills_path(format: :pdf, search: params[:search], date_range: params[:date_range], per_page: params[:per_page], direction: params[:direction], sort: params[:sort], page: params[:page]) %></li>
                        <li><%= link_to I18n.t('helpers.link_to.download_csv'), bills_path(format: :csv, search: params[:search], date_range: params[:date_range], per_page: params[:per_page], direction: params[:direction], sort: params[:sort], page: params[:page]) %></li>
                        <li><%= link_to I18n.t('helpers.link_to.download_xls'), bills_path(format: :xls, search: params[:search], date_range: params[:date_range], per_page: params[:per_page], direction: params[:direction], sort: params[:sort], page: params[:page]) %></li>
                      </ul>
                    </div>
                  </div>
                    <% end %>
                  </div>
                  <div class="clearfix"></div>
                </div>

              <% if cannot? :destroy_multiple, Bill %>
                </div>
              <% end %>
              </div>
                <table aria-describedby="datatable_info" class="table table-bordered dataTable" id="datatable">
                <thead>
                  <tr>
                    <% if can? :destroy_multiple, Bill %>
                      <th><div class="checkbox checkbox-primary"><%= check_box_tag "selectAll", "selectAll" %><label for="checkbox1"></label></div></th>
                    <% end %>
                    <% [:id, :number, :issued_date, :date_of_payment, :amount, :get_person, :get_bill_status].each do |column| %>
                      <%= sortable column, I18n.t('helpers.label.bill.' + column.to_s) %>
                    <% end %>
                    <th></th>
                  </tr>
                  </thead>
                  <tbody>
                    <% unless @bills.nil? %>
                      <% @bills.each do |bill| %>
                        <% if bill.get_bill_status == I18n.t('bill_statuses.unpaid') %>
                          <tr class="red">
                        <% else %>
                          <tr>
                        <% end %>
                            <% if can? :destroy, bill %>
                              <td><div class="checkbox checkbox-info"><%= check_box_tag "bills[]", bill.id %><label for="checkbox1"></label></div></td>
                            <% end %>
                            <td><%= link_to bill.id, bill_path(bill.id) %></td>
                            <% [:number, :issued_date, :date_of_payment, :amount, :get_person, :get_bill_status].each do |col| %>
                              <td><%= bill.send(col) %></td>
                            <% end %>
                            <% if can? :update, bill or can? :destroy, bill or !bill.bill_attachments.empty? %>
                              <td class="text-center">
                                <% if can? :show, bill and !bill.bill_attachments.empty? %>
                                  <%= link_to download_attachments_bill_path(bill) do %>
                                    <i class="fa fa-save"></i>
                                  <% end %>
                                <% end %>
                                <% if can? :update, bill %>
                                  <%= link_to edit_bill_path(bill) do %>
                                    <i class="fa fa-pencil"></i>
                                  <% end %>
                                <% end %>
                                <% if can? :destroy, bill %>
                                  <%= link_to bill_path(bill), method: :delete, data: {confirm: I18n.t('helpers.link_to.bill.destroy_single_message', bill: bill.id)} do %>
                                    <i class="fa fa-times"></i>
                                  <% end %>
                                <% end %>
                                <% if (can? :update, bill) && (bill.bill_status_id == BillStatus.find_by(name: I18n.t('bill_statuses.unpaid')).id) %>
                                  <%= link_to bill_path(bill, bill:{bill_status_id: BillStatus.find_by(name: I18n.t('bill_statuses.pay')).id}, redirect_to_list: true), method: :put do %>
                                    <i class="fa fa-dollar"></i>
                                  <% end %>
                                <% end %>
                              </td>
                            <% end %>
                          </tr>
                      <% end %>
                    <% end %>
                  </tbody>
                </table>
                <div class="form-pagination">
                  <% unless @bills.nil? %>
                    <%= will_paginate @bills %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for :js_scripts do %>
  <script>
    $('#selectAll').click(function() {
       if (this.checked) {
           $(':checkbox').each(function() {
               this.checked = true;
           });
       } else {
          $(':checkbox').each(function() {
               this.checked = false;
           });
       }
    });
  </script>
<% end %>

app/views/bills/index.pdf.erb
<% @bills.each do |bill| %>
  <%= render 'form', bill: bill %>
<% end %>

app/views/bills/index.xls.erb
<%= render 'layouts/xls', items: @bills, fields: [:id, :number, :issued_date, :date_of_payment, :amount, :get_person, :get_bill_status] %>

app/views/bills/new.html.erb
<div class="cl-mcont">
  <div class="row">
    <div class="col-md-12">
      <div class="block-flat">
        <div class="header">
          <h3><%= I18n.t('headlines.' + controller_name.singularize + '.new') %></h3>
        </div>
        <div class="content">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bills/new_attachment.html.erb
<div class="cl-mcont">
  <div class="row">
    <div class="col-md-12">
      <div class="block-flat attach">
       <div class="header">
          <h3>Dodaj załącznik</h3>
        </div>
        <%= form_for :bill_attachments, url: url_for(controller: 'bills', action: 'create_attachment'), html: {class: "form-horizontal group-border-dashed"} do |b| %>
        <%= hidden_field :bill_id, params[:id] %>
        <div class="form-group">
          <%= b.label I18n.t('helpers.label.person.person_attachments.attachment'), class: "col-sm-3 control-label" %>
          <div class="col-sm-6 file_field">
            <%= b.file_field :attachment, multiple: true, name: "bill_attachments[attachment][]", type: "file", class: "filestyle" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-9">
            <div class="pull-right">
              <%= link_to I18n.t('helpers.link_to.cancel'), :back, class: "btn btn-default btn-rad" %>
              <%= b.submit I18n.t('helpers.submit.bill_attachments.create'), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
      <% content_for :js_scripts do %>
        <script type="text/javascript">
          $(":file").filestyle('buttonText', "Wybierz załączniki");
        </script>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bills/show.html.erb
<div class="cl-mcont">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="block-flat">
        <div class="header">
          <h3><%= @bill.number %></h3>
        </div>
        <div class="content">
          <table class="no-border">
            <tbody class="no-border-y">
              <% [:number, :id, :issued_date, :date_of_payment, :amount, :person_id, :created_by_id, :bill_status_id].each do |row| %>
              <tr>
                <td><%=  I18n.t('helpers.label.bill.' + row.to_s) %></td>
                <% if row == :person_id or row == :created_by_id %>
                  <td>
                    <% unless @bill.send(row).nil? %>
                      <%= Person.find(@bill.send(row)).get_name_and_surname_or_username %>
                    <% end %>
                  </td>
                <% elsif row == :bill_status_id %>
                  <td><%= BillStatus.find(@bill.send(row)).name %></td>
                <% else %>
                  <td><%= @bill.send(row) %></td>
                <% end %>
              </tr>
            <% end %>
            <td><strong><%= I18n.t('helpers.label.bill.attachment') %></strong></td><td></td>
            <% @bill.bill_attachments.each do |a| %>
              <tr>
                <td><%= link_to I18n.t('helpers.label.bill.attachment_number') + a.id.to_s, download_attachment_bills_path(a) %></td>
                <td>
                  <% if can? :destroy_attachment, @bill %>
                    <%= link_to  I18n.t('helpers.label.bill.attachment_remove'), attachment_path(a), method: :delete, data: {confirm: I18n.t('helpers.link_to.bill.attachment_destroy_message', number: a.id)} %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            <tr>
              <% if can? :add_attachment, @bill %>
              <td><%= link_to I18n.t('helpers.link_to.bill.attachment_create'), new_attachment_bills_path(id: @bill.id) %></td><td><%= link_to I18n.t('helpers.link_to.bill.attachments_download'),download_attachments_bill_path(@bill) unless @bill.bill_attachments.empty? %></td>
              <% end %>
            </tr>
            </tbody>
          </table>
        </div>
        <div class="button-line">
          <% if can? :update, @bill %>
            <%= link_to I18n.t('helpers.link_to.edit'), edit_bill_path(@bill), class:"btn btn-success" %>
          <% end %>
          <% if can? :destroy, @bill %>
            <%= link_to I18n.t('helpers.link_to.destroy'), bill_path(@bill), method: :delete, data: {confirm: I18n.t('helpers.link_to.bill.destroy_single_message', bill: @bill.id)}, class:"btn btn-danger" %>
          <% end %>
          <% if can? :show, @bill %>
            <div class="btn-group">
              <button type="button" class="btn btn-info" data-toggle="dropdown"><%= I18n.t('helpers.link_to.download') %></button>
                <button aria-expanded="false" type="button" class="btn btn-info btn-mono2 dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to I18n.t('helpers.link_to.download_pdf'), bill_path(format: :pdf) %></li>
                  <li><%= link_to I18n.t('helpers.link_to.download_csv'), bill_path(format: :csv) %></li>
                  <li><%= link_to I18n.t('helpers.link_to.download_xls'), bill_path(format: :xls) %></li>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bills/show.pdf.erb
<%= render 'form', bill: @bill %>

app/views/bills/show.xls.erb
<%= render 'layouts/xls', items: [@bill], fields: [:id, :number, :issued_date, :date_of_payment, :amount, :get_person, :get_bill_status] %>