config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  resources :equipments, :attachments
  resources :orders do
    collection do
      delete 'destroy_multiple'
      get 'import_file'
      post 'import'
      post 'change_status'
      get 'change_status'
    end
  end
  resources :people do
    collection do
      delete 'destroy_multiple'
      get 'new_attachment'
      get 'download_attachment'
      post 'create_attachment'
    end
    member do
      get 'download_attachments'
    end
  end
  resources :alerts do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :bills do
    collection do
      delete 'destroy_multiple'
      get 'new_attachment'
      get 'download_attachment'
      post 'create_attachment'
    end
    member do
      get 'download_attachments'
    end
  end

  get "own_alerts" => "alerts#own"
  get "my_alerts" => "alerts#my"
  get "my_bills" => "bills#my"
  get "my_orders" => "orders#my"
  get "orders_cancelled_from_this_month" => "orders#orders_cancelled_from_this_month"
  get "orders_diagnosis_from_this_month" => "orders#orders_diagnosis_from_this_month"
  get "orders_repair_from_this_month" => "orders#orders_repair_from_this_month"
  get "orders_verification_from_this_month" => "orders#orders_verification_from_this_month"
  root 'panels#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  extend Search
  include GenerateCSV
  belongs_to :person, counter_cache: true
  belongs_to :order_status
  validates :phone, :date, :who_took_the_order_id, :order_status_id, presence: true
  validates :amount, numericality: {greater_then_or_equal_to: 0}, allow_nil: true
  validate :check_phone, :check_amount
  validate :check_status, on: :update
  after_initialize :set_default_status_if_nil
  validate :check_if_record_exist_in_database, on: :create
  scope :my_orders, lambda { |current_person| where(person_id: current_person.id)}
  scope :started_orders_from_this_month, -> { where("extract(month from date) = ?", Time.now.month) }
  scope :orders_verification_from_this_month, -> { where("extract(month from date) = ? AND order_status_id = ?", Time.now.month, OrderStatus.find_by_name(I18n.t('order_statuses.verification')).id) }
  scope :orders_repair_from_this_month, -> { where("extract(month from date) = ? AND order_status_id = ?", Time.now.month, OrderStatus.find_by_name(I18n.t('order_statuses.repair')).id) }
  scope :orders_diagnosis_from_this_month, -> { where("extract(month from date) = ? AND order_status_id = ?", Time.now.month, OrderStatus.find_by_name(I18n.t('order_statuses.diagnosis')).id) }
  scope :orders_cancelled_from_this_month, -> { where("extract(month from date) = ? AND order_status_id = ?", Time.now.month, OrderStatus.find_by_name(I18n.t('order_statuses.cancelled')).id) }
  after_save :check_reason

  def check_amount
    unless self.amount.nil?
      if self.amount < 0
        errors.add(:amount,  I18n.t('model_errors.amount'))
      end
    end
  end

  def check_if_record_exist_in_database
    if Order.where(phone: phone, reason: reason, date: date, amount: amount, place: place,
                   who_took_the_order_id: who_took_the_order_id, person_id: person_id, equipment_type: equipment_type,
                   equipment_name: equipment_name, accident: accident, address: address, visit: visit).present?
      errors.add(:id, I18n.t('model_errors.order'))
    end
  end

  def check_phone
    phone_number = self.send(:phone)
    unless phone_number.nil?
      unless phone_number.empty?
        if (7..16).include? phone_number.length
          errors.add(:phone, I18n.t('model_errors.phone_number', field: I18n.t('helpers.label.order.phone').downcase)) unless phone_number.strip.delete("() +-").is_number?
        else
          errors.add(:phone, I18n.t('model_errors.phone_number', field: I18n.t('helpers.label.order.phone').downcase))
        end
      end
    end
  end

  def check_reason
    unless self.reason.nil?
      unless self.reason.empty?
        unless status == I18n.t('order_statuses.cancelled')
          update_attributes(reason: nil)
        end
      end
    end
  end

  def check_status
    if ([I18n.t('order_statuses.diagnosis'), I18n.t('order_statuses.repair')].include? Order.find(self.id).status) and (status == I18n.t('order_statuses.cancelled')) and (person.has_role? I18n.t('roles.partner'))
      errors.add(:status, I18n.t('orders.change_status.couldnt_change_from_cancelled', cancelled: I18n.t('order_statuses.cancelled'), status: Order.find(self.id).status))
    end
  end

  def get_date
    self.date.strftime("%d-%m-%Y")
  end

  def get_order_status
    unless self.order_status.nil?
      self.order_status.name
    end
  end

  def get_person
    unless self.person_id.nil?
      self.person.get_name_and_surname_or_username
    end
  end

  def get_time
    self.date.strftime("%H:%M")
  end

  def status
    OrderStatus.find(self.order_status_id).name
  end

  def get_who_took_the_order
    wtto = self.who_took_the_order_id
    unless wtto.nil?
      if Person.where(id: wtto).exists?
        Person.find(wtto).get_name_and_surname_or_username
      end
    end
  end

  def self.set_previous_month(year, month)
    if month == 0
      year -= 1
      month = 12
    elsif month < 0
      year -= 1
      month = 12 + month
    end
    [year, month]
  end

  def self.import(file, current_person)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    error_rows = []
    (2..spreadsheet.last_row).each_with_index do |i, index|
      row = HashInsensitive[[header, spreadsheet.row(i)].transpose]
      row.values.each do |value_to_strip|
        if !value_to_strip.to_s.empty? and value_to_strip.is_a? String
          value_to_strip.strip!
        end
      end
      if Person.find_by_username(row["PARTNER"]).nil? or Person.find_by_username(row["PRACOWNIK INFOLINII"]).nil?
        error_rows << index+2
      else
        order = Order.new
        order.person = Person.find_by_username(row["PARTNER"])
        order.equipment_type = row["SPRZET"]
        order.equipment_name = row["MARKA"]
        order.accident = row["AWARIA"]
        order.place = row["MIASTO"]
        order.address = row["ADRES"]
        order.phone = row["TELEFON"]
        unless row["STATUS"].nil?
          unless OrderStatus.find_by_name(row["STATUS"]).nil?
            order.order_status_id = OrderStatus.find_by_name(row["STATUS"])
          end
        end
        order.reason = row["POWOD"]
        if !row["DATA"].nil? and !row["GODZINA"].nil?
          if file.path.end_with? "csv" or file.path.end_with? "CSV"
            order.date = (row["DATA"] + " " + row["GODZINA"]).to_datetime
          else
            order.date = (row["DATA"].to_s + " " + (Time.at(row["GODZINA"]) - Time.zone.utc_offset).strftime("%H:%M:%S")).to_datetime
          end
        elsif !row["DATA"].nil? and row["GODZINA"].nil?
          order.date = (row["DATA"]).to_datetime
        end
        order.visit = row["WIZYTA"]
        if row["PRACOWNIK INFOLINII"].nil?
          order.who_took_the_order_id = current_person.id
        else
          order.who_took_the_order_id = Person.find_by_username(row["PRACOWNIK INFOLINII"]).id
        end
        unless order.save
          error_rows << index+2
        end
      end
    end
    error_rows
  end

  def self.open_spreadsheet(file)
    if File.extname(file.original_filename) == ".csv"
      if Roo::CSV.new(file.path).row(2).to_s.count("\;") >= 6
        Roo::CSV.new(file.path, csv_options: {col_sep: "\;"})
      elsif Roo::CSV.new(file.path).row(2).to_s.count("\t") >= 6
        Roo::CSV.new(file.path, csv_options: {col_sep: "\t"})
      else
        Roo::CSV.new(file.path)
      end
    else
      case File.extname(file.original_filename)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Nieznany format pliku: #{file.original_filename}"
      end
    end
  end

  def self.orders_by_month(year, month)
    order_counter = []
    year_and_month = Order.set_previous_month(year, month)
    if Time.now.year == year_and_month[0] and Time.now.month == year_and_month[1]
      end_day = Time.now.day
    else
      end_day = Date.parse(year_and_month[0].to_s + "-" + year_and_month[1].to_s + "-1").end_of_month.day
    end
    (1..end_day).each do |day|
      order_counter << Order.where("cast(date as date) = ?", Date.parse(year_and_month[0].to_s + "-" + year_and_month[1].to_s + "-" + day.to_s)).count
    end
    order_counter
  end

  def self.orders_cancelled_from_previous_month
    year_and_month = Order.set_previous_month(Time.now.year, Time.now.month - 1)
    Order.where("extract(month from date) = ? AND extract(year from date) = ? AND order_status_id = ?", year_and_month[1], year_and_month[0], OrderStatus.find_by_name(I18n.t('order_statuses.cancelled')))
  end

  def self.orders_from_previous_month
    year_and_month = Order.set_previous_month(Time.now.year, Time.now.month - 1)
    Order.where("extract(month from date) = ? AND extract(year from date) = ?", year_and_month[1], year_and_month[0])
  end

  def self.counter_orders_by_month(year, month)
    order_counter = Order.orders_by_month(year, month)
    order_counter.inject{|sum,x| sum + x}
  end

  def self.six_last_counter_orders_by_month(year, month)
    results = []
    year_and_month = Order.set_previous_month(year, month)
    6.times do |index|
      results.unshift [month - index, Order.counter_orders_by_month(year_and_month[0], year_and_month[1] - index)]
    end
    results
  end

  def self.search(search, range)
    normal_fields = [:id, :equipment_type, :equipment_name, :accident, :place, :address, :phone, :reason, :date]
    special_fields = {
      person_id: [Person, [:name, :surname]],
      order_status_id: [OrderStatus, :name],
      who_took_the_order_id: [Person, [:name, :surname]]
    }
    super(search, normal_fields, special_fields, range)
  end

  def self.special_fields_for_sort
    {
      "get_person": "people.surname",
      "get_who_took_the_order": "who_took_the_order.surname",
      "order_id": "id",
      "get_date": "date",
      "get_time": "date"
    }
  end

  def set_default_status_if_nil
    @status = OrderStatus.find_by_id(self.order_status_id)
    unless @status
      self.order_status_id = OrderStatus.find_by_name( I18n.t('order_statuses.verification')).id
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < GenericController
  before_action :all_people_and_order_statuses, only: [:new, :edit, :update, :create]
  before_action :per_page, only: [:my, :orders_cancelled_from_this_month, :orders_diagnosis_from_this_month, :orders_repair_from_this_month, :orders_verification_from_this_month]
  helper_method :current_user, :how_many_percent_by_status

  def change_status
    respond_to do |f|
      f.js do
        if params[:selected].present?
          order = Order.find(params[:selected_order])
          order.order_status =  OrderStatus.find_by_name(params[:selected])
          if params[:reason].present?
            order.reason = params[:reason]
          end
          if order.valid?
            if order.save
              render status:200, json: t('.success')
            else
              render status: 422, json: t('.error')
            end
          else
            render status: 422, json: order.errors.messages.first[1].first
          end
        else
          destroy_multiple
        end
      end
    end
  end

  def create
    params[:order][:who_took_the_order_id] = current_user.id if params[:order][:who_took_the_order_id].nil?
    super
  end

  def destroy_multiple
    controller = controller_name.to_s
    if params[controller] == nil
      flash[:alert] = t('.no_checked')
    else
      errors = 0
      params[controller].each do |item_id|
      @item = eval(controller_name.singularize.humanize).where(id: item_id)
        if @item.count == 1
          if @item.first.destroy
          else
            errors += 1
          end
        else
          errors += 1
        end
      end
      if errors == 0
        if params[controller].count == 1
          flash[:success] = t('.success_one')
        elsif params[controller].count > 1
          flash[:success] = t('.success_more', how_many: params[controller].count)
        end
      else
        removed = params[controller].count - errors
        if removed == 0
          flash[:error] = t('.error_no_one')
        elsif removed == 1
          flash[:error] = t('.error_one', how_many: params[controller].count)
        elsif removed > 1
          flash[:error] = t('.error_more', how_many_destroyed: removed, how_many: params[controller].count)
        end
      end
    end
    render js: "window.location = '/orders'"
  end

  def how_many_percent_by_status(status)
    how_many = 0
    @orders.each do |order|
      if order.status == status
        how_many += 1
      end
    end
    how_many
  end

  def import
    errors = Order.import(params[:file], current_person)
    if errors.size > 0
      flash[:error] = t('.error', parameter: errors.size, number: errors)
      redirect_to orders_path
    else
      flash[:success] = t('.success')
      redirect_to orders_path
    end
  end

  def import_file
  end

  def index
    respond_to do |format|
      super
      if params[:sort] == "get_who_took_the_order"
        @orders = Order.search(params[:search], params[:date_range])
        @orders = @orders.sort_by{|order| Person.find(order.who_took_the_order_id).surname}
        if params[:direction] == "desc"
          @orders.reverse!
        end
        @orders = @orders.paginate(page: params[:page],:per_page => @per_page)
      else
        @orders = Order.search(params[:search], params[:date_range]).order(sort_column + " " + sort_direction).paginate(page: params[:page],:per_page => @per_page)
      end
      @orders.includes(:person)
      format.csv do
        send_data @orders.to_csv
      end
      format.html
      format.pdf do
        pdf(I18n.t('.pdf.orders') + "_#{I18n.t('.pdf.from')}_" + Time.new.strftime("%Y-%m-%d_%H-%M"))
      end
      format.xls
    end
  end

  def my
    @orders = Order.my_orders(current_person).search(params[:search], params[:date_range]).order(sort_column + " " + sort_direction).paginate(page: params[:page],:per_page => per_page)
    render :index
  end

  def orders_cancelled_from_this_month
    @orders = Order.orders_cancelled_from_this_month.search(params[:search], params[:date_range]).order(sort_column + " " + sort_direction).paginate(page: params[:page],:per_page => @per_page)
    unless current_person.role.name == "administrator"
      @orders = @orders.where(person_id: current_person.id)
    end
    render :index
  end

  def orders_diagnosis_from_this_month
    @orders = Order.orders_diagnosis_from_this_month.search(params[:search], params[:date_range]).order(sort_column + " " + sort_direction).paginate(page: params[:page],:per_page => @per_page)
    unless current_person.role.name == "administrator"
      @orders = @orders.where(person_id: current_person.id)
    end
    render :index
  end

  def orders_repair_from_this_month
    @orders = Order.orders_repair_from_this_month.search(params[:search], params[:date_range]).order(sort_column + " " + sort_direction).paginate(page: params[:page],:per_page => @per_page)
    unless current_person.role.name == "administrator"
      @orders = @orders.where(person_id: current_person.id)
    end
    render :index
  end

  def orders_verification_from_this_month
    @orders = Order.orders_verification_from_this_month.search(params[:search], params[:date_range]).order(sort_column + " " + sort_direction).paginate(page: params[:page],:per_page => @per_page)
    unless current_person.role.name == "administrator"
      @orders = @orders.where(person_id: current_person.id)
    end
    render :index
  end

  def show
    respond_to do |format|
      format.csv do
        if can? :get_who_took_the_order, Order
          send_data Order.where(id: @order.id).to_csv()
        else
          send_data Order.where(id: @order.id).to_csv("partner")
        end
      end
      format.html
      format.pdf do
        pdf(I18n.t('.pdf.order') + "_" + @order.id.to_s + "_#{I18n.t('.pdf.from')}_" + Time.new.strftime("%Y-%m-%d_%H-%M"))
      end
      format.xls
    end
  end

  private
  def all_people_and_order_statuses
    @people = Person.where(role: Role.find_by_name(I18n.t('roles.partner'))).order(:surname, :name)
    @employees = Person.where(role: Role.find_by_name(I18n.t('roles.employee').to_sym)).order(:surname, :name)
    @partners = Person.where(role: Role.find_by_name(I18n.t('roles.partner').to_sym)).order(:surname, :name)
    @order_statuses = OrderStatus.all
    if @order.valid?
      @actual_person = Person.find(@order.person.id).id
      @current_status = OrderStatus.find(@order.order_status_id)
      @actual_who_took_the_order = Person.find(@order.who_took_the_order_id).id
    else
      @current_status = OrderStatus.find_by_name(I18n.t('order_statuses.verification'))
      if params[:order].nil? or params[:order][:person_id].nil?
        @actual_person = nil
      else
        @actual_person = params[:order][:person_id]
      end
    end
  end

  def order_params
    params.require(:order).permit(:phone, :reason, :date, :amount, :place, :address, :who_took_the_order_id, :person_id, :equipment_type, :equipment_name, :order_status_id, :status, :accident)
  end

  def per_page
    if params[:per_page].nil? or params[:per_page] == ""
      if can? :show, :default_1000_records
        @per_page = 1000
      else
        @per_page = 25
      end
    else
      @per_page = params[:per_page]
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<% content_for :body_attributes do %>
  data-no-turbolink="true"
<% end %>
<div class="cl-mcont">
  <div class="row">
    <% values_and_colors = [[:repair, "#4D90FD"], [:diagnosis, "#FD6A5E"], [:cancelled, "#B450B2"], [:verification, "#B450B2"]] %>
    <% 4.times do |time| %>
      <div class="col-sm-6 col-md-6 col-lg-3">
        <div class="block-flat">
          <div class="header">
            <% value = how_many_percent_by_status(I18n.t('charts.order.' + values_and_colors[time][0].to_s)) %>
            <h3><%= I18n.t('charts.order.' +  values_and_colors[time][0].to_s) + ": " + value.to_s %></h3>
          </div>
          <div class="content text-center">
            <div class="epie-chart" data-barcolor="<%= values_and_colors[time][1] %>" data-trackcolor="#F3F3F3" data-percent="<%= value / @orders.size.to_f * 100 %>"><span>0%</span></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="block-flat">
        <div class="header">
          <h3><%= I18n.t('headlines.' + controller_name.singularize + '.index') %></h3>
        </div>
        <div class="content">
          <div class="table-responsive orders">
            <div id="datatable_wrapper" class="dataTables_wrapper form-inline" role="grid">
              <div class="row">
                <div class="col-sm-12">
                  <div id="datatable_filter" class="dataTables_filter">
                    <%= render 'search/form', special_path: request.original_url.split("/").last.split("?").first %>
                      <% if can? :create, Order %>
                        <%= form_tag import_orders_path, multipart: true, class: "form-horizontal group-border-dashed" do %>
                          <div class="import-button">
                             <span class="file-input btn btn-primary btn-file">
                              <%= file_field_tag :file, multiple: true, class: "" %><%= I18n.t('headlines.order.import') %>
                            </span>
                          </div>
                        <% end %>
                      <% end %>
                    <%= form_tag change_status_orders_path, id: 'main_form', remote: true do |f|%>
                      <div class="buttons-list-edit">
                        <%= link_to I18n.t('helpers.link_to.order.create'), new_order_path, class:"btn btn-success btn-rad" if can? :new, Order %>
                        <% unless @orders.nil? %>
                          <%= submit_tag I18n.t('helpers.link_to.order.destroy_multiple'), class:"btn btn-danger btn-rad" if can? :destroy, Order %>
                        <% end %>
                        <% counter = 0 %>
                        <% @orders.each do |order| %>
                          <% if can? :show, order %>
                            <% counter += 1 %>
                          <% end %>
                        <% end %>
                        <% if counter == @orders.size %>
                          <div class="btn-group">
                            <button type="button" class="btn btn-info" data-toggle="dropdown"><%= I18n.t('helpers.link_to.download') %></button>
                            <button aria-expanded="false" type="button" class="btn btn-info btn-mono2 dropdown-toggle" data-toggle="dropdown">
                              <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><%= link_to I18n.t('helpers.link_to.download_pdf'), orders_path(format: :pdf, search: params[:search], date_range: params[:date_range], date_range: params[:date_range], per_page: params[:per_page], direction: params[:direction], sort: params[:sort], page: params[:page]) %></li>
                              <li><%= link_to I18n.t('helpers.link_to.download_csv'), orders_path(format: :csv, search: params[:search], date_range: params[:date_range], date_range: params[:date_range], per_page: params[:per_page], direction: params[:direction], sort: params[:sort], page: params[:page]) %></li>
                              <li><%= link_to I18n.t('helpers.link_to.download_xls'), orders_path(format: :xls, search: params[:search], date_range: params[:date_range], date_range: params[:date_range], per_page: params[:per_page], direction: params[:direction], sort: params[:sort], page: params[:page]) %></li>
                            </ul>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                </div>
                <table aria-describedby="datatable_info" class="table table-bordered dataTable" id="datatable">
                  <thead>
                    <tr>
                      <% if can? :destroy, Order %>
                        <th>
                          <div class="checkbox checkbox-primary"><%= check_box_tag "selectAll", "selectAll" %><label for="checkbox1"></label></div>
                        </th>
                      <% end %>
                      <% [:order_id, :get_person, (:get_who_took_the_order if can? :get_who_took_the_order, Order), :equipment_type, :equipment_name, :accident, :place, :address, :phone, :reason, :get_date, :get_time, :order_status_id].each do |column| %>
                        <% if column != nil and column != :date %>
                          <%= sortable column, I18n.t('helpers.label.order.' + column.to_s) %>
                        <% end %>
                      <% end %>
                      <% if can? :update, @orders or can? :destroy, @orders %>
                        <th></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% unless @orders.nil? %>
                      <% @orders.each do |order| %>
                        <% if order.status == I18n.t('order_statuses.verification')%>
                          <tr class="red">
                          <% else %>
                            <tr>
                            <% end %>
                            <% if can? :destroy, order %>
                              <td>
                                <div class="checkbox checkbox-info"><%= check_box_tag "orders[]", order.id %><label for="checkbox1"></label></div>
                              </td>
                            <% end %>
                            <td><%= link_to order.id, order_path(order.id) %></td>
                            <% [:get_person, (:get_who_took_the_order if can? :get_who_took_the_order, Order), :equipment_type, :equipment_name, :accident, :place, :address, :phone, :reason, :get_date, :get_time].each do |col| %>
                              <% unless col.nil? %>
                                <% if col != :get_date %>
                                  <td><%= order.send(col) %></td>
                                <% else %>
                                  <td class="nospaceing"><%= order.send(col) %></td>
                                <% end %>
                              <% end %>
                            <% end %>
                            <td>
                              <% if current_person.get_role != I18n.t('roles.employee') %>
                                <%= select_tag order.id, options_for_select(OrderStatus.all.uniq.collect{|o| [o.name, o.id]}, selected: [order.order_status_id]), {class: "select-status form-control"} %>
                              <% else %>
                                <%= order.get_order_status %>
                              <% end %>
                            </td>
                            <% if can? :update, order or can? :destroy, order %>
                              <td class="text-center">
                                <% if can? :update, order %>
                                  <%= link_to edit_order_path(order) do %>
                                    <i class="fa fa-pencil"></i>
                                  <% end %>
                                <% end %>
                                <% if can? :destroy, order %>
                                  <%= link_to order_path(order), method: :delete, data: {confirm: I18n.t('helpers.link_to.order.destroy_single_message', order: order.id)} do %>
                                    <i class="fa fa-times"></i>
                                  <% end %>
                                <% end %>
                              </td>
                            <% end %>
                          </tr>
                        <% end %>
                      <% end %>
                    <% end %>
                  </tbody>
                </table>
                <div class="form-pagination">
                  <% unless @orders.nil? %>
                    <%= will_paginate @orders %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% content_for :js_scripts do %>
    <script>
      $('#selectAll').click(function() {
        if (this.checked) {
          $(':checkbox').each(function() {
            this.checked = true;
          });
        } else {
          $(':checkbox').each(function() {
            this.checked = false;
          });
        }
      });
      $('.epie-chart').easyPieChart({
        animate: 1000,
        lineWidth: 8,
        size: 150,
        onStep: function(val){//Update current value while animation
          $("span", this.$el).html(parseInt(val) + "%");
        }
      });
      $('input[type=file]').change(function(event){
        var target = $(event.target);

        if(target.val() != ''){
          $(target.parents('form').get(0)).submit(); //better ways to do it ^^

          event.stopPropagation();
          return false;
        }
      });
      $('.select-status').change(function() {
        var reason, selected, selected_order;
        selected = void 0;
        selected_order = void 0;
        reason = void 0;
        selected = $('<input>').attr('type', 'hidden').attr('name', 'selected').val($('#' + this.id + ' option:selected').text());
        $('#main_form').append($(selected));
        if ($.isNumeric(this.parentElement.parentElement.firstElementChild.nextElementSibling.textContent)) {
          selected_order = $('<input>').attr('type', 'hidden').attr('name', 'selected_order').val(this.parentElement.parentElement.firstElementChild.nextElementSibling.textContent);
        } else {
          selected_order = $('<input>').attr('type', 'hidden').attr('name', 'selected_order').val(this.parentElement.parentElement.firstElementChild.textContent);
        }
        if (selected[0].value == "<%= I18n.t('order_statuses.cancelled') %>"){
          reason = $('<input>').attr('type', 'hidden').attr('name', 'reason').val(prompt("<%= I18n.t('orders.change_status.reason_prompt') %>"));
          $('#main_form').append($(reason));
        } else {
          $('input[name=reason]').remove();
        }
        $('#main_form').append($(selected_order));
        $('#main_form').submit();
      });
      $(document).ready(function() {
        return $("#main_form").on("ajax:error ajax:success", function(e, xhr, status, error) {
          if(xhr !== "window.location = '/orders'"){
            $.gritter.add({
              title: (xhr.status == 200) ? '<%= I18n.t('notifications.success') %>' : '<%= I18n.t('notifications.error') %>',
              text: xhr.responseText,
              time: (xhr.status == 200) ? '20000' : '60000'
            });
          }
        });
      });
    </script>
  <% end %>

app/views/orders/show.html.erb
<div class="cl-mcont">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="block-flat">
        <div class="header">
          <h3><%=I18n.t('headlines.order.show', order: @order.id) %></h3>
        </div>
        <div class="content">
          <table class="no-border">
            <tbody class="no-border-y">
              <% [:phone, :reason, :get_date, :get_time, :amount, :place, :address, (:get_who_took_the_order if can? :get_who_took_the_order, Order), :get_person, :equipment_type, :equipment_name, :get_order_status, :accident].each do |row| %>
                <% unless row.nil? %>
                  <tr>
                    <td><%=  I18n.t('helpers.label.order.' + row.to_s) %></td>
                    <td><%= @order.send(row) %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="button-line">
          <% if can? :update, @order %>
            <%= link_to I18n.t('helpers.link_to.edit'), edit_order_path(@order), class:"btn btn-success" %>
          <% end %>
          <% if can? :destroy, @order %>
            <%= link_to I18n.t('helpers.link_to.destroy'), order_path(@order), method: :delete, data: {confirm: I18n.t('helpers.link_to.order.destroy_single_message', order: @order.id)}, class:"btn btn-danger" %>
          <% end %>
          <% if can? :show, @order %>
            <div class="btn-group">
              <button type="button" class="btn btn-info" data-toggle="dropdown"><%= I18n.t('helpers.link_to.download') %></button>
                <button aria-expanded="false" type="button" class="btn btn-info btn-mono2 dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to I18n.t('helpers.link_to.download_pdf'), order_path(format: :pdf) %></li>
                  <li><%= link_to I18n.t('helpers.link_to.download_csv'), order_path(format: :csv) %></li>
                  <li><%= link_to I18n.t('helpers.link_to.download_xls'), order_path(format: :xls) %></li>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.pdf.erb
<%= render 'form', order: @order %>