config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  resources :equipments, :attachments
  resources :orders do
    collection do
      delete 'destroy_multiple'
      get 'import_file'
      post 'import'
      post 'change_status'
      get 'change_status'
    end
  end
  resources :people do
    collection do
      delete 'destroy_multiple'
      get 'new_attachment'
      get 'download_attachment'
      post 'create_attachment'
    end
    member do
      get 'download_attachments'
    end
  end
  resources :alerts do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :bills do
    collection do
      delete 'destroy_multiple'
      get 'new_attachment'
      get 'download_attachment'
      post 'create_attachment'
    end
    member do
      get 'download_attachments'
    end
  end

  get "own_alerts" => "alerts#own"
  get "my_alerts" => "alerts#my"
  get "my_bills" => "bills#my"
  get "my_orders" => "orders#my"
  get "orders_cancelled_from_this_month" => "orders#orders_cancelled_from_this_month"
  get "orders_diagnosis_from_this_month" => "orders#orders_diagnosis_from_this_month"
  get "orders_repair_from_this_month" => "orders#orders_repair_from_this_month"
  get "orders_verification_from_this_month" => "orders#orders_verification_from_this_month"
  root 'panels#index'

end

app/views/layouts/_xls.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Fachowcy">
    <Table>
      <Row>
        <% fields.each do |field| %>
          <Cell><Data ss:Type="String"><%= I18n.t("helpers.label." + controller_name.singularize + "." + field.to_s) %></Data></Cell>
        <% end %>
      </Row>
    <% items.each do |item| %>
      <Row>
        <% fields.each do |field| %>
          <Cell><Data ss:Type="String"><%= item.send(field) %></Data></Cell>
        <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DamZam - Panel Partnera</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,300,600,700,800&subset=latin,latin-ext', 'data-turbolinks-track' => true %>
</head>
<body
  <% if content_for?(:body_attributes) %>
    <%= yield(:body_attributes) %>
  <% end %>>
  <div style="opacity: 1; margin-left: 0px;" id="cl-wrapper">
    <% if person_signed_in? %>
      <div class="cl-sidebar">
        <div class="cl-toggle"><i class="fa fa-bars"></i></div>
        <div class="cl-navblock">
          <div class="menu-space">
            <div class="content">
              <!--LOGO-->
              <div class="sidebar-logo">
                <div class="logo">
                    <a href=""></a>
                </div>
              </div>
              <div class="side-user">
                <% if !current_person.nil? %>
                  <h2><%= current_person.get_name_and_surname_or_username %></h2>
                  <h5><%= current_person.get_role.titleize %></h5>
                <% else %>
                  <h2>Niezalogowany</h2>
                <% end %>
              </div>
              <!--Menu-->
              <ul class="cl-vnavigation">
                <%= get_li(root_path) %>
                  <%= link_to root_path do %>
                    <i class="fa fa-home"></i><span>Strona główna</span>
                  <% end %>
                </li>
                <% if can? :create, Order or can? :index, Order or can? :my, Order or can? :create, Order %>
              <li class="parent"><a href="#"><i class="fa fa-gift"></i><span>Zlecenia</span></a>
                    <ul class="sub-menu">
                      <% if can? :create, Order %>
                        <%= get_li(new_order_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.create_order'), new_order_path %>
                        </li>
                      <% end %>
                      <% if can? :index, Order %>
                        <%= get_li(orders_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.orders_list'), orders_path %>
                        </li>
                      <% end %>
                      <% if can? :my, Order %>
                        <%= get_li(my_orders_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.my_orders_list'), my_orders_path %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
                <% if can? :create, Person or can? :index, Person or can? :show, Person %>
                  <li class="parent"><a href="#"><i class="fa fa-user"></i><span>Fachowcy</span></a>
                    <ul class="sub-menu">
                      <% if can? :create, Person %>
                        <%= get_li(new_person_path) %>
                          <%= link_to  I18n.t('helpers.link_to.panel.new_person'), new_person_path %>
                        </li>
                      <% end %>
                      <% if can? :index, Person %>
                        <%= get_li(people_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.people_list'), people_path %>
                        </li>
                      <% end %>
                      <% if can? :show, Person %>
                        <%= get_li(person_path(current_person)) %>
                          <%= link_to I18n.t('helpers.link_to.panel.current_person'), person_path(current_person) %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
                <% if can? :create, Bill or can? :index, Bill or can? :my, Bill %>
                  <li class="parent"><a href="#"><i class="fa fa-money"></i><span>Rachunki</span></a>
                    <ul class="sub-menu">
                      <% if can? :create, Bill %>
                        <%= get_li(new_bill_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.create_bill'), new_bill_path %>
                        </li>
                      <% end %>
                      <% if can? :index, Bill %>
                        <%= get_li(bills_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.bills_list'), bills_path %>
                        </li>
                      <% end %>
                      <% if can? :my, Bill %>
                        <%= get_li(my_bills_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.show_my_bills'), my_bills_path %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
                <% if can? :new, Alert or can? :manage, Alert or can? :my, Alert or can? :own, Alert %>
                  <li class="parent"><a href="#"><i class="fa fa-info"></i><span>Alerty</span></a>
                    <ul class="sub-menu">
                      <% if can? :new, Alert %>
                        <%= get_li(new_alert_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.new_alert'), new_alert_path %>
                        </li>
                      <% end %>
                      <% if can? :manage, Alert %>
                        <%= get_li(alerts_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.show_all_alerts'), alerts_path %>
                        </li>
                      <% end %>
                      <% if can? :my, Alert %>
                        <%= get_li(my_alerts_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.show_my_alerts', how_many: Alert.my_alerts(current_person).count), my_alerts_path %>
                        </li>
                      <% end %>
                      <% if can? :own, Alert %>
                        <%= get_li(own_alerts_path) %>
                          <%= link_to I18n.t('helpers.link_to.panel.show_own_alerts', how_many: Alert.own_alerts(current_person)), own_alerts_path %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="text-right collapse-button" style="padding:7px 9px;">
            <button id="sidebar-collapse" class="btn btn-default" style=""><i style="color:#fff;" class="fa fa-angle-left"></i></button>
          </div>
        </div>
      </div>
      <% end %>
<!--    <div class="container-fluid" id="pcont"></div>-->
    <!-- TOP BAR -->
    <% if person_signed_in? %>
        <div id="head-nav" class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-collapse">
              <ul class="nav navbar-nav navbar-right user-nav">
                <h4><%= link_to "Wyloguj #{current_person.get_name_and_surname_or_username}", destroy_person_session_path, method: :delete %></h4>
                <%= render 'modals/show' unless @first_alert == nil %>
              </ul>
              <ul class="nav navbar-nav not-nav">
              <!-- Menu Notification Items -->
              </ul>
            </div>
          </div>
        </div>
     <% end %>
    <div class="col-sm-6 col-md-6">
      <% [:success, :notice, :alert, :error].each do |value| %>
        <% unless flash[value] == nil %>
          <%= javascript_tag do %>
            <% if value == :error %>
              <% @time = 60000 %>
            <% else %>
              <% @time = 20000 %>
            <% end %>
            $.gritter.add({
              title: '<%= I18n.t('notifications.' + value.to_s) %>',
              text: '<%= flash[value] %>',
              time: '<%= @time %>'
            });
          <% end %>
        <% end %>
      <% end %>
    </div>
    <%= yield %>
  </div>
  <%= yield :js_scripts %>
</body>
</html>
<script type="text/javascript">
 var width = screen.width,
      height = screen.height;
  setInterval(function () {
      if (screen.width !== width || screen.height !== height) {
          width = screen.width;
          height = screen.height;
          $(window).trigger('resolutionchange');
          if(width <= 767){
            $('#cl-wrapper').removeClass("sb-collapsed");
          }
      }
  }, 50);
  </script>

app/views/layouts/application.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <script>
      function number_pages() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = decodeURIComponent(z[1]);}
        var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
        for(var i in x) {
          var y = document.getElementsByClassName(x[i]);
          for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
        }
      }
    </script>
    <style>
      body{
        text-align: center;
      }
      h1{
        color: #B25798;
        margin-top: 0px;
        width: 18cm;
      }
      tr > td{
        vertical-align: top;
      }
      tr > td:first-child {
        color: #7F2A67;
        text-align: right;
        width: 30%;
      }
      tr > td:last-child {
        color: #2c3e50;
        text-align: left;
        width: 70%;
      }
      #header{
        margin-bottom: 0.5cm;
        float: right;
      }
      #header > img{
        top: 0px;
        width: 2cm;
      }
      #content{
        left: 0px;
        float:left;
      }
      table{
        width: 100%;
        margin-bottom: 1.5cm;
      }
    </style>
  </head>
  <body>
    <div id="header">
      <%= wicked_pdf_image_tag("logo.png") %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>